language: go

go:
  - 1.13.x
  - tip

os:
  - linux

services:
  - docker

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

branches:
  only:
    - master

script:
  - make style codecov

jobs:
  include:
    - stage: integration
      name: "Integration Tests"
      script:
        - make it
