language: go

go:
  - 1.13.x
  - tip

os:
  - linux

services:
  - docker

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+.*$/

script:
  - make style codecov
jobs:
  include:
    - stage: integration
      name: "Integration Tests"
      script:
        - make it
    - stage: tag
      name: "Tag For Release"
      script:
        - export OLD_VERSION=$(make version)
        - git config --local user.name "xmidt-su"
        - git config --local user.email "chqsv-webpa@comcast.com"
        - export TAG=$(cat CHANGELOG.md | perl -0777 -ne 'print "$1" if /.*## \[Unreleased\]\s+## \[(v\d+.\d+.\d+)\].*/s')
        - if [[ "$TAG" != "" && "$TAG" != "$OLD_VERSION" ]]; then git tag "$TAG"; fi
    - stage: deploy
      script: skip
      before_deploy:
        - make release-artifacts
        - export RELEASE_BODY=$(cat CHANGELOG.md | perl -0777 -ne 'print "$1\n" if /.*## \[$ENV{TRAVIS_TAG}\]\s(.*?)\s+## \[(v\d+.\d+.\d+)\].*/s')
      deploy:
        on:
          all_branches: true
          tags: true
        provider: releases
        api_key: "$GH_TOKEN"
        file: ./ignore/*
        release_notes: "$RELEASE_BODY"
        skip_cleanup: true