language: go

go:
  - 1.13.x
  - tip

os:
  - linux

services:
  - docker

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+.*$/

script:
  - make style codecov

jobs:
  include:
    - stage: integration
      name: "Integration Tests"
      script:
        - make it
    - stage: deploy
      script: skip
      before_deploy:
        - make release-artifacts
      deploy:
        on:
          tags: true
          all_branches: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*
        provider: releases
        api_key: "$GH_TOKEN"
        file: ./ignore/*
        skip_cleanup: true