language: go

go:
  - 1.13.x
  - tip

os:
  - linux

services:
  - docker

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+.*$/

script:
  - make style codecov
jobs:
  include:
    - stage: integration
      name: "Integration Tests"
      script:
        - make it
    - stage: tag
      name: "Tag For Release"
      before_script:
        - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
      script:
        - export OLD_VERSION=$(make version)
        - git config --global user.name "kcajmagic"
        - git config --global user.email "jackrmurdock@gmail.com"
        - export TAG=$(cat CHANGELOG.md | perl -0777 -ne 'print "$1" if /.*## \[Unreleased\]\s+## \[(v\d+.\d+.\d+)\].*/s')
        - export NOTES=$(cat CHANGELOG.md | perl -0777 -ne 'print "$1\n" if /.*## \[$ENV{TAG}\]\s(.*?)\s+## \[(v\d+.\d+.\d+)\].*/s')
        - echo "$TAG"
        - echo "$NOTES"
        - if [[ "$TAG" != "" && "$TAG" != "$OLD_VERSION" ]]; then git tag -a "$TAG" -m "$NOTES"; git push origin "$TAG"; echo $?; fi
    - stage: release
      name: "Make a Release"
      script: skip
      before_deploy:
        - make release-artifacts
      deploy:
        on:
          all_branches: true
          tags: true
        provider: releases
        api_key: "$GH_TOKEN"
        file: ./.ignore/*
        skip_cleanup: true