language: go

go:
  - "1.11.x"

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

branches:
  only:
    - master

before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS


script:
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - zip -r source.zip . && mkdir dist && mv source.zip dist
  - go get github.com/mitchellh/gox
  - gox -osarch "linux/amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"

after_success:
  - TRAVIS_TAG=`cat version.txt`

deploy:
  provider: releases
  prerelease: true
  overwrite: true
  api_key: "$AUTH_TOKEN_BUILD"
  file:
    - dist/testing_linux_amd64
  skip_cleanup: true
  on:
    condition: "$TRAVIS_PULL_REQUEST = false"