language: go

go:
  - "1.11.x"

services:
  - docker

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

branches:
  only:
    - master

before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS
  - LAST_BUILD=`cat version.txt`
  - TRAVIS_TAG=`ci/scripts/rc_bump.sh $LAST_BUILD`

jobs:
  include:
    - stage: docker
      script:
        - docker build -t test:local .
        - docker run -d -p 8080:8080 test:local
        - docker ps -a
        - curl localhost:8080

script:
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - go get github.com/haya14busa/goverage
  - goverage -coverprofile=coverage.txt ./...

after_success:
  -  bash <(curl -s https://codecov.io/bash)


