language: go

go:
  - 1.11.x
  - tip

os:
  - linux
  - osx

services:
  - docker

branches:
  only:
    - master

before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS
  - LAST_BUILD=`cat version.txt`
  - TRAVIS_TAG=`ci/scripts/rc_bump.sh $LAST_BUILD`

script:
  - make style codecov

jobs:
  include:
    - stage: integration
      name: "Integration Tests"
      script:
        - make it

