language: go

go:
  - "1.11.x"

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

branches:
  only:
    - master

before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS
  - LAST_BUILD=`cat version.txt`
  - TRAVIS_TAG=`ci/scripts/rc_bump.sh $LAST_BUILD`


script:
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - go get github.com/haya14busa/goverage
  - goverage -coverprofile=coverage.txt ./...

after_success:
  -  bash <(curl -s https://codecov.io/bash)
  - TRAVIS_TAG=`cat version.txt`-rc.$TRAVIS_BUILD_NUMBER

before_deploy:
  - go get github.com/mitchellh/gox
  - gox -osarch "linux/amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" github.com/kcajmagic/testing
  - echo $TRAVIS_TAG > version.txt
#  - git config --global user.email "travis@travis-ci.org"
#  - git config --global user.name "Travis CI"
  - git commit -am "[skip travis] Travis build $TRAVIS_BUILD_NUMBER update version to $TRAVIS_TAG"
  - git push origin master

deploy:
  provider: releases
  prerelease: true
  overwrite: true
  api_key: "$AUTH_TOKEN_BUILD"
  file:
    - dist/testing_linux_amd64
  name: CI Build
  body: "$TRAVIS_TAG $TRAVIS_COMMIT_MESSAGE"
  on:
    all_branches: true
    condition: "$TRAVIS_PULL_REQUEST = false"